### ISSUE TITLE
Cetak Struk

### ISSUE THREAD

**Issue by rezamukti** [ajikamaludin-dev/react-native-kasiraja-mobile#1]
ini aplikasi simpel dan keren banget Kak,
lebih sempurna lagi ada cetak struknya kak
karena utk toko retail dibutuhkan bukti pembelian.

good luck ka

**Comment by ajikamaludin** [comment]
## InProgress
Halo Kak , saya sedang mengusahakan untuk membeli thermal print guna development dan test print

### Support me

<a href="https://trakteer.id/ajikamaludin" target="_blank"><img id="wse-buttons-preview" src="https://cdn.trakteer.id/images/embed/trbtn-blue-2.png" height="40" style="border:0px;height:40px;" alt="Trakteer Saya"></a>

**Comment by rezamukti** [comment]
ok sy sudah trakteer ya semoga bisa bermanfaat utk terus berkarya
